<?php  //[STAMP] cd9814e72e664fb32985de998cfac521
namespace SprykerEcoTest\Service\ComputopApi\_generated;

// This class was automatically generated by build task
// You should not change it manually as it will be overwritten on next build
// @codingStandardsIgnoreFile

trait ComputopApiServiceTesterActions
{
    /**
     * @return \Codeception\Scenario
     */
    abstract protected function getScenario();

    
}
