<?php  //[STAMP] 02850096ab268197759ae63b9a0dfda3
namespace SprykerEcoTest\Service\ComputopApi\_generated;

// This class was automatically generated by build task
// You should not change it manually as it will be overwritten on next build
// @codingStandardsIgnoreFile

trait ComputopApiServiceTesterActions
{
    /**
     * @return \Codeception\Scenario
     */
    abstract protected function getScenario();


}
