<?php

/**
 * MIT License
 * Use of this software requires acceptance of the Evaluation License Agreement. See LICENSE file.
 */

namespace SprykerEco\Shared\ComputopApi;

interface ComputopApiConstants
{
    const MERCHANT_ID = 'COMPUTOP_API:MERCHANT_ID';
    const BLOWFISH_PASSWORD = 'COMPUTOP_API:BLOWFISH_PASSWORD';
    const HMAC_PASSWORD = 'COMPUTOP_API:HMAC_PASSWORD';

    const EASY_CREDIT_STATUS_ACTION = 'COMPUTOP_API:EASY_CREDIT_STATUS_ACTION';
    const EASY_CREDIT_AUTHORIZE_ACTION = 'COMPUTOP_API:EASY_CREDIT_AUTHORIZE_ACTION';

    const AUTHORIZE_ACTION = 'COMPUTOP_API:AUTHORIZE_ACTION';
    const CAPTURE_ACTION = 'COMPUTOP_API:CAPTURE_ACTION';
    const REVERSE_ACTION = 'COMPUTOP_API:REVERSE_ACTION';
    const INQUIRE_ACTION = 'COMPUTOP_API:INQUIRE_ACTION';
    const REFUND_ACTION = 'COMPUTOP_API:REFUND_ACTION';
    
    const RESPONSE_MAC_REQUIRED = 'COMPUTOP_API:RESPONSE_MAC_REQUIRED';
}
