<?php

/**
 * MIT License
 * Use of this software requires acceptance of the Evaluation License Agreement. See LICENSE file.
 */

namespace SprykerEco\Shared\ComputopApi;

interface ComputopApiConstants
{
    const MERCHANT_ID = 'COMPUTOPAPI:MERCHANT_ID';
    const BLOWFISH_PASSWORD = 'COMPUTOPAPI:BLOWFISH_PASSWORD';
    const HMAC_PASSWORD = 'COMPUTOPAPI:HMAC_PASSWORD';

    const EASY_CREDIT_STATUS_ACTION = 'COMPUTOPAPI:EASY_CREDIT_STATUS_ACTION';
    const EASY_CREDIT_AUTHORIZE_ACTION = 'COMPUTOPAPI:EASY_CREDIT_AUTHORIZE_ACTION';

    const AUTHORIZE_ACTION = 'COMPUTOPAPI:AUTHORIZE_ACTION';
    const CAPTURE_ACTION = 'COMPUTOPAPI:CAPTURE_ACTION';
    const REVERSE_ACTION = 'COMPUTOPAPI:REVERSE_ACTION';
    const INQUIRE_ACTION = 'COMPUTOPAPI:INQUIRE_ACTION';
    const REFUND_ACTION = 'COMPUTOPAPI:REFUND_ACTION';
    
    const RESPONSE_MAC_REQUIRED = 'COMPUTOPAPI:RESPONSE_MAC_REQUIRED';
}
